name: ServerHelp
author: ScottApple_
version: 1.0
description: Helps players out on the server.
main: me.scottapple_.serverhelp.ServerHelp
commands:
  tutorial:
    description: Shows you how to play the server.
  staff:
    description: Shows you all the staff, so they know who is boss.
  shreload:
    description: Reloads the ServerHelp's configuration file.
  commands:
    description: Shows you how to view what permissions/commands you have.
  twitter:
    description: Shows you the twitter link.
  website:
    description: Shows you the website link.
  donate:
    description: Shows you the donation link.
  facebook:
    description: Shows you the facebook link.
  youtube:
    description: Shows you the youtube link.
  email:
    description: Shows you the support email.
  vote:
    description: Shows you link(s) to the voting site(s).
  thread:
    description: Shows you a link to an important thread.
  link:
    description: Shows you a link to somewhere.
