Version: 1
Messages:
  Prefix: "&3[&fServerHelp]&r "
  DonateMsg: ""
  YoutubeMsg: ""
  WebsiteMsg: ""
  FacebookMsg: ""
  TwitterMsg: ""
  CommandsMsg: ""
  EmailMsg: ""
  StaffMsg: ""
  TutorialMsg: ""
  TeamspeakMsg: ""
  MumbleMsg: ""
  VoteMsg: ""
  ThreadMsg: ""
  LinkMsg: ""
  NoPermMsg: ""
Backend:
  vote: true