name: ServerHelp
author: ScottApple_ #Plus the help of FallenYouth
version: 1.0.0
main: me.scottapple.ServerHelp.Serverhelp
description: A plugin that helps you with your server!

commands:
  donate:
    description: Does stuff
  youtube:
    description: Does stuff
  website:
    description: Does stuff
  facebook:
    description: Does stuff
  twitter:
    description: Does stuff
  commands:
      description: Does stuff
  email:
      description: Does stuff
  staff:
      description: Does stuff
  tutorial:
      description: Does stuff
  tutorial:
      description: Does stuff
  mumble:
      description: Does stuff
  shreload:
      description: Does stuff
  vote:
      description: Does stuff
  thread:
      description: Does stuff
  link:
      description: Does stuff
permissions:
  serverhelp.donate:
    description: /donate
    default: op
  serverhelp.youtube:
    description: /youtube
    default: op
  serverhelp.website:
    description: /website
    default: op
