name: ServerHelp
author: ScottApple_ #Plus the help of FallenYouth
version: 1.0.0
main: me.scottapple.ServerHelp.Serverhelp
description: A plugin that helps you with your server!

commands:
  donate:
    description: Does stuff
  youtube:
    description: Does stuff
  website:
    description: Does stuff
  facebook:
    description: Does stuff
  twitter:
    description: Does stuff
  commands:
      description: Does stuff
  email:
      description: Does stuff
  staff:
      description: Does stuff
  tutorial:
      description: Does stuff
  teamspeak:
      description: Does stuff
  mumble:
      description: Does stuff
  shreload:
      description: Does stuff
  vote:
      description: Does stuff
  thread:
      description: Does stuff
  link:
      description: Does stuff
permissions:
  serverhelp.donate:
    description: /<command>
    default: op
  serverhelp.youtube:
    description: /<command>
    default: op
  serverhelp.website:
    description: /<command>
    default: op
  serverhelp.facebook:
      description: /<command>
      default: op
  serverhelp.twitter:
      description: /<command>
      default: op
  serverhelp.commands:
      description: /<command>
      default: op
  serverhelp.email:
      description: /<command>
      default: op
  serverhelp.staff:
      description: /<command>
      default: op
  serverhelp.tutorial:
      description: /<command>
      default: op
  serverhelp.teamspeak:
      description: /<command>
      default: op
  serverhelp.mumble:
        description: /<command>
        default: op
  serverhelp.shreload:
        description: /<command>
        default: op
  serverhelp.vote:
        description: /<command>
        default: op
  serverhelp.thread:
        description: /<command>
        default: op
  serverhelp.link:
        description: /<command>
        default: op