name: ServerHelp
author: ScottApple_ #Plus the help of FallenYouth
version: 1.0.0
main: me.scottapple.ServerHelp.Serverhelp
description: A plugin that helps you with your server!

commands:
  donate:
    description: Does stuff
  youtube:
    description: Does stuff
  website:
    description: Does stuff
  facebook:
    description: Does stuff
  twitter:
    description: Does stuff
  donate:
    description: Does stuff
permissions:
  serverhelp.donate:
    description: /donate
    default: op